language: java
sudo: required
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: trellis-ldp

stages:
  - test
  - deploy

before_script:
  - psql -c 'create database trellis;' -U postgres

env:
    - JOB=check

jobs:
    fast_finish: true

    allow_failures:
      - env: JOB=sonatype
      - env: JOB=docker
      - env: JOB=aws

    include:
        # JDK 8
        - name: "Java 8"
          stage: test
          jdk: oraclejdk8
          script: ./gradlew check install jacocoRootReport --scan
          after_success: ./gradlew coveralls sonarqube

        # JDK 11
        - name: "Java 11"
          stage: test
          jdk: oraclejdk11
          script: ./gradlew check install

        # deploy to Sonatype
        - name: "Publish to Sonatype"
          stage: deploy
          jdk: oraclejdk8
          env: JOB=sonatype
          if: branch = master AND type = push
          # Only automate the publication of SNAPSHOTS
          script: if [[ $(./gradlew -q getVersion) == *SNAPSHOT* ]]; then ./gradlew publish ; fi

        # deploy to Docker hub
        - name: "Publish to Docker hub"
          stage: deploy
          jdk: oraclejdk8
          env: JOB=docker
          # TODO add support for maintenance branches
          if: branch = master AND type = push
          before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          script: if [[ $(./gradlew -q getVersion) == *SNAPSHOT* ]]; then ./gradlew dockerPush dockerPushDevelop; else ./gradlew dockerPush dockerPushLatest; fi

        # deploy to AWS
        - name: "Publish JavaDocs"
          stage: deploy
          jdk: oraclejdk8
          env: JOB=aws
          if: branch = master AND type = push
          script: ./gradlew apidocs
          deploy:
              provider: s3
              access_key_id: $AWS_ACCESS_KEY
              secret_access_key: $AWS_SECRET_KEY
              bucket: $AWS_BUCKET
              skip_cleanup: true
              local_dir: docs/apidocs/$(./gradlew -q getVersion)
              upload-dir: docs/trellis-ext-aws/$(./gradlew -q getVersion)/apidocs
              default_text_charset: 'utf-8'

